### ISSUE TITLE
Plugin no funciona en Brave

### ISSUE THREAD

**Issue by Raynou** [Gian12315/refactored-robot#4]
Al momento de ejecutar el plugin en Brave el navegador bloquea las peticiones al servidor Apache.

**Comment by Gian12315** [comment]
No sera problema del como Brave maneja el cache o cookies?

**Comment by Raynou** [comment]
En efecto, se tenía que configurar las cookies de brave para permitir mandar las peticiones. Aquí la esta la fuente que consulte https://community.brave.com/t/brave-blocks-requests-to-my-backend-endpoints/183173
