### ISSUE TITLE
Plugin no controla caso en cuando no hay nadie en cámara.

### ISSUE THREAD

**Issue by Raynou** [Gian12315/refactored-robot#5]
Cuando el estudiante no está en cámara, se tapa la cara o simplemente se mueve mucho (haciendo que no se le pueda tomar una foto clara) el servicio de AWS no puede determinar los sentimientos de la persona, por lo que la librería regresa respuesta vacía en el arreglo de sentimientos.

**Comment by Gian12315** [comment]
Si la respuesta es vacia, entonces no guardes el registro en la base de datos

No lo modifiques en la libreria, deja que el usuario de la libreria lo maneje de manera local, para poder considerar el uso de la libreria para el plugin de los examenes

IE. Si hay 3 o mas tomas de fotos vacias, entonces el wey no tiene la camara bien puesta y se le impide seguir hasta que se acomode para la camara

**Comment by Raynou** [comment]
Ok
